# uninstall.cmake - Uninstall script using install_manifest.txt

# Get the install manifest file generated by CMake
set(MANIFEST_FILE "${CMAKE_BINARY_DIR}/install_manifest.txt")

if(NOT EXISTS ${MANIFEST_FILE})
    message(FATAL_ERROR "install_manifest.txt not found. Please run 'make install' first.")
endif()

# Read all lines from the install manifest
file(READ ${MANIFEST_FILE} INSTALL_LIST)

# Split the list into individual files (one per line)
string(REPLACE "\n" ";" INSTALL_LIST ${INSTALL_LIST})

# Loop over each installed file and delete it
foreach(FILE IN LISTS INSTALL_LIST)
    # Remove any empty lines or extra spaces
    string(STRIP ${FILE} FILE)
    if(FILE)
        message(STATUS "Uninstalling: ${FILE}")
        file(REMOVE ${FILE})
    endif()
endforeach()

# Optionally, remove the install_manifest.txt itself
file(REMOVE ${MANIFEST_FILE})

message(STATUS "Uninstall completed.")
